name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Daily
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python update_repos.py
      - run: |
          git add README.md
          git commit -m "Update repositories" || true
          git push
