name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Daily
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "REPO-LIST"
          feed_list: "https://github.com/DarylFernandes99.atom"
          max_post_count: 6
          template: '<a href="$url"><img width="400" src="https://github-readme-stats.vercel.app/api/pin/?username=DarylFernandes99&repo=$title&theme=dark&hide_border=true&bg_color=0d1117&title_color=58a6ff&text_color=c9d1d9&icon_color=40c463" /></a>'
